version: "3.9"

services:
  backend:
    build: .
    container_name: ambassador_backend
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=ambassador
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0.32
    restart: always
    container_name: ambassador-db
    environment:
      - MYSQL_DATABASE=ambassador
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=oot
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0
    container_name: ambassador-redis
    ports:
      - "6379:6379"